repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=5000"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff-format
        name: ruff format
      - id: ruff
        name: ruff lint
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        args: ["--config-file", "pyproject.toml", "--ignore-missing-imports"]
        additional_dependencies: [types-requests, pydantic]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        name: interrogate
        args: ["--config", "pyproject.toml"]
