# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

# on:
#     push:
#       branches: [ main ]
#     pull_request:
#       branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codecov
        pip install torch pytest numpy 
        
    
    - name: Install package
      run: |
        pip install -e .  

    - name: Run tests with pytest and collect coverage
      run: |
        pytest --cov=TorchSOM tests/